# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

$rxVersion = '~> 4.1.2'

target 'Dragon Android Transfer' do
	# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
	use_frameworks!
    
    inhibit_all_warnings! #Ignore warnings, Specific = , :inhibit_warnings => true
    
	pod 'MASShortcut'
#    pod 'Sparkle'
#    pod 'PLCrashReporter', '~> 1.2'
	pod 'RxSwift', $rxVersion
	pod 'RxCocoa', $rxVersion
	
	# Pods for Dragon Android Transfer
	
    target 'Dragon Android TransferTests' do
		inherit! :search_paths
		pod 'RxBlocking', $rxVersion
		pod 'RxTest',     $rxVersion
	end
	
	target 'Dragon Android TransferUITests' do
		inherit! :search_paths
		# Pods for testing
	end

end
